/**
 * C-01: pin preprocessor behavior for every construct in the vetted
 * generated subset (norns docs/vetted-subset.md). The norns generator
 * only emits these constructs; this suite guarantees the preprocessor
 * keeps handling them (and keeps *rejecting* the documented traps) so
 * upgrades of civet/pug/svelte-preprocess can't silently break
 * generated apps.
 */

import { describe, expect, test } from 'bun:test';

import { compile as civet } from '@danielx/civet';
import { preprocess, compile as svelteCompile } from 'svelte/compiler';

import { nornsPreprocess } from '../src/preprocess.js';

const civetJs = (src) => civet(src, { sync: true, js: true });

async function preprocessNorn(source, filename = 'Page.n') {
	const result = await preprocess(source, nornsPreprocess(), { filename });
	return result.code;
}

async function compileNorn(source, filename = 'Page.n') {
	const code = await preprocessNorn(source, filename);
	return svelteCompile(code, { generate: 'client', runes: true }).js.code;
}

/* ------------------------------------------------------------------ */
/* Civet server files (.c) — the generated lib/ constructs             */
/* ------------------------------------------------------------------ */

describe('vetted .c constructs compile through civet', () => {
	test('header comment passes through', () => {
		const js = civetJs('// GENERATED by `norns generate` from specs/orders.tron — do not edit.\nx := 1\n');
		expect(js).toContain('GENERATED by');
		expect(js).toContain('const x = 1');
	});

	test('namespace, named, and default imports', () => {
		const js = civetJs(
			[
				`import * as dz from 'drizzle-orm'`,
				`import { eq } from 'drizzle-orm'`,
				`import priceBody from '$custom/orders/actions/price.c'`,
				`export x := [dz, eq, priceBody]`
			].join('\n')
		);
		expect(js).toContain(`import * as dz from 'drizzle-orm'`);
		expect(js).toContain(`import { eq } from 'drizzle-orm'`);
		expect(js).toContain(`import priceBody from '$custom/orders/actions/price.c'`);
	});

	test('`export X := {}` is an exported const', () => {
		expect(civetJs('export submit := { a: 1 }')).toContain('export const submit = { a: 1 }');
	});

	test('civet operator keywords are safe as quoted object keys', () => {
		const js = civetJs(`ops := { 'and': 1, 'or': 2, 'not': 3, eq: 4 }`);
		expect(js).toContain(`{ 'and': 1, 'or': 2, 'not': 3, eq: 4 }`);
	});

	test('JS-style async arrow bodies with braces and return', () => {
		const js = civetJs(
			[
				'export run := async ({ input, container, user }) => {',
				`\tconst db = container.resolve('db')`,
				`\tif (!input.id) throw new Error('missing id')`,
				'\tawait db.ping()',
				'\treturn { ok: true }',
				'}'
			].join('\n')
		);
		expect(js).toContain('async ({ input, container, user }) =>');
		expect(js).toContain('return { ok: true }');
	});

	test('template literals survive', () => {
		expect(civetJs('frag := dz.sql`1 = 1`')).toContain('dz.sql`1 = 1`');
	});
});

describe('documented .c traps stay trapped', () => {
	test('`isnt` does NOT compile to !== (bare identifier hazard)', () => {
		// If a civet upgrade ever makes this compile to `!==`, the ban can
		// be lifted — until then the generator must keep emitting `!==`.
		const js = civetJs('x := a isnt b');
		expect(js).not.toContain('!==');
	});

	test('`and` in brace imports is a parse error', () => {
		expect(() => civetJs(`import { and } from 'drizzle-orm'`)).toThrow();
	});

	test('unquoted `and` object key happens to work in plain literals (quoting stays defensive)', () => {
		// The hard trap is brace imports (above). Plain object literals
		// compile today — pinned so we notice if that ever regresses in
		// either direction.
		expect(civetJs('ops := { and: 1 }')).toContain('{ and: 1 }');
	});

	test('async generator method shorthand currently compiles (excluded for minimalism, not breakage)', () => {
		expect(civetJs('obj := {\n\tasync *gen() {\n\t\tyield 1\n\t}\n}')).toContain('async *gen()');
	});
});

/* ------------------------------------------------------------------ */
/* .n components — the generated routes/ constructs                    */
/* ------------------------------------------------------------------ */

const PAGE = [
	'section.norns-page',
	'\tKanban(data!="{data.board}" onMove="?/submit")',
	'',
	'<script>',
	`\timport Kanban from '$lib/ui/Kanban.n'`,
	'\t{ data, form } := $props()',
	'\tselected := $state(null)',
	'</script>',
	''
].join('\n');

describe('vetted .n constructs preprocess and compile', () => {
	test('the generated page shape compiles end-to-end', async () => {
		const js = await compileNorn(PAGE);
		expect(js).toContain('Kanban');
	});

	test('plain tag + simple class shorthand', async () => {
		const code = await preprocessNorn('section.norns-page\n\tp hello\n');
		expect(code).toContain('<section class="norns-page"');
	});

	test('component tag with != svelte-expression attributes', async () => {
		const code = await preprocessNorn(PAGE);
		expect(code).toContain('data="{data.board}"');
		expect(code).toContain('onMove="?/submit"');
	});

	test('+if / +else mixins become svelte blocks', async () => {
		const src = ['+if(\'data.ok\')', '\tp yes', '+else', '\tp no', ''].join('\n');
		const code = await preprocessNorn(src);
		expect(code).toContain('{#if data.ok}');
		expect(code).toContain('{:else}');
		expect(code).toContain('{/if}');
	});

	test('+each with ` as ` becomes a svelte each block', async () => {
		const src = [
			'+each(\'data.rows as row\')',
			'\tp {row.id}',
			'',
			'<script>',
			'\t{ data } := $props()',
			'</script>',
			''
		].join('\n');
		const code = await preprocessNorn(src);
		expect(code).toContain('{#each data.rows as row}');
		expect(svelteCompile(code, { generate: 'client', runes: true }).js.code).toBeTruthy();
	});

	test('`:=` props destructure compiles to const $props()', async () => {
		const code = await preprocessNorn(PAGE);
		expect(code).toMatch(/const\s*\{\s*data,\s*form\s*\}\s*=\s*\$props\(\)/);
	});

	test('`:=` local state compiles to const $state', async () => {
		const code = await preprocessNorn(PAGE);
		expect(code).toMatch(/const selected = \$state\(null\)/);
	});

	test('auto-wrap: bare pug content needs no <template> block', async () => {
		const code = await preprocessNorn('p hello\n');
		expect(code).toContain('<p>hello</p>');
	});
});

describe('documented .n traps stay trapped', () => {
	test('+each with `of` form maps verbatim into a broken each block', async () => {
		const src = ['+each(\'row of data.rows\')', '\tp {row.id}', ''].join('\n');
		const code = await preprocessNorn(src);
		expect(code).toContain('{#each row of data.rows}');
		expect(() => svelteCompile(code, { generate: 'client', runes: true })).toThrow();
	});

	test('fractional class shorthand is rescued by the class rewriter', async () => {
		// Raw Pug would parse `.5` as a new class; norns-core's
		// rewritePugClasses routes it into attribute form. The generator
		// still emits only [a-z0-9-] shorthand — this pins the safety net.
		const code = await preprocessNorn('div.gap-2.5 x\n');
		expect(code).toContain('class="gap-2.5"');
	});

	test('leading {#if} on a template line is not a svelte block after pug', async () => {
		let ok = null;
		try {
			ok = await preprocessNorn('{#if data.ok}\n\tp yes\n{/if}\n');
		} catch {
			/* throwing is the expected trap outcome */
		}
		if (ok !== null) expect(ok).not.toContain('{#if data.ok}\n<p>');
	});
});
